name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: yarn install
    - name: Run tests
      run: yarn test:unit
    - name: build
      run: yarn build
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: yarn install
    - name: Run linter
      run: yarn lint --no-fix --max-warnings 0
